# The project
PROJECT_NAME: Dharmafly Docs
# Version number as a string
VERSION: '1.0'
GITHUB_PROJECT_URL: https://github.com/dharmafly/dharmafly-docs

THEME: forest
DOWNLOAD_LINKS:
TWITTER_PROJECT_URL:
LANG:
SCRIPTS:
QUOTE:
GA_ID:
sections:
 - path: /index.html
   name: Overview
 - path: /reference/index.html
   name: Reference

DOWNLOAD_LINKS:
  - text: Dharmafly Docs
    subtext: v{{ version }}
    href: https://github.com/dharmafly/dharmafly-docs/zipball/gh-pages
    title: zipped   

############ Deprecated 

# Link from overview to reference
REFERENCE_LINK_TEXT: 

GITHUB_ZIP_URL: 

############ Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
