#########################################
# project site config

project_name: noodle
project_url: https://github.com/dharmafly/noodle
version: '0.3.1'
# options: forest, ocean, horus, seagrass, sundae, slate
theme: ocean
twitter_url: https://twitter.com/dharmafly
# options: javascript, css, html5
lang: javascript
scripts:
  - src: //ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
#  - src: https://raw.github.com/dharmafly/PROJECT-REPO/master/PROJECT.js
quote:
#- quote: 
#- cite: 
# analytics
ga_id: UA-34978047-5
download_links:
  - text: Edge
    subtext: (master)
    href: https://github.com/dharmafly/noodle/zipball/master
    title: The repo's latest codebase (zip). Potentially unstable.
sections:
 - path: /index.html
   name: Overview
 - path: /reference/index.html
   name: Reference

######## END project site config ########
